In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
a = np.arange(8,41,2)
b = np.array(range(10,59,3))
print(a)
print(type(a))
print(b)
print(type(b))

[ 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
<class 'numpy.ndarray'>
[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58]
<class 'numpy.ndarray'>


In [3]:
dt = {
    "Pizza": np.arange(8,41,2),
    "Price": np.arange(10,59,3)
}

In [4]:
dt

{'Pizza': array([ 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40]),
 'Price': array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52, 55, 58])}

In [5]:
df = pd.DataFrame(dt)

In [6]:
df.head()

,Pizza,Price
0,8,10
1,10,13
2,12,16
3,14,19
4,16,22


In [7]:
X = df[['Pizza']]
y = df['Price']

In [8]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, test_size=0.2)

In [9]:
Xtrain

,Pizza
2,12
6,20
14,36
5,18
7,22
13,34
1,10
12,32
0,8
8,24


In [10]:
Xtest

,Pizza
16,40
15,38
9,26
3,14


In [11]:
lr = LinearRegression()
lr.fit(Xtrain, ytrain)

LinearRegression()

In [12]:
lr.predict([[10]])

C:\Users\Gyanp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([13.])

In [13]:
lr.intercept_

np.float64(-1.999999999999993)

In [14]:
lr.coef_

array([1.5])

In [17]:
df = pd.read_csv("C:/Users/Gyanp/Downloads/gradetable.csv")

In [18]:
df

,EnrollmentNo,Name,Percentage
0,Elnct19203,Jeevan Das,7.9
1,Elnct1834,Vivek Parihar,B
2,Eoist234,Sonam Pathak,8.3
3,Eoist8976,Komal Sadani,A
4,Ebist3425,Aarti Verma,B
5,Ebist7634,Naazneen Bano,6.5
6,Etit9807,Rishi kotlebhage,8.8
7,Etit8320,Joy Patra,A+
8,Esirt1001,Ayush Bundela,B+
9,Esirt1200,Piyush Waoo,7.4


In [19]:
df['num'] = pd.to_numeric(df['Percentage'], errors = 'coerce')

In [20]:
df['num']

0     7.9
1     NaN
2     8.3
3     NaN
4     NaN
5     6.5
6     8.8
7     NaN
8     NaN
9     7.4
10    NaN
11    NaN
Name: num, dtype: float64

In [22]:
df['cat'] = df['Percentage'].where(pd.to_numeric(df['Percentage'], errors = 'coerce').isna())

In [23]:
df['cat']

0     NaN
1       B
2     NaN
3       A
4       B
5     NaN
6     NaN
7      A+
8      B+
9     NaN
10    85%
11    68%
Name: cat, dtype: object